mongo_url = 'mongodb://127.0.0.1:27017/'
data_len = 100
TOP55 = ['Kay Mann', 'Outlook Migration Team <Outlook Migration Team/Corp/Enron@ENRON>', 'Kate Symes',
         'Germany, Chris </O=ENRON/OU=NA/CN=RECIPIENTS/CN=CGERMAN>', 'Richard B Sanders',
         'Steffes, James D. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JSTEFFE>', 'Benjamin Rogers', 'Susan M Scott',
         'Carol St Clair', 'Debra Perlingiere',
         'Phillip M Love', 'Enron General Announcements </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MBX_ANNCENRON>',
         'Dasovich, Jeff </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JDASOVIC>', 'Elizabeth Sager',
         'Sara Shackleton', 'Davis, Pete </O=ENRON/OU=NA/CN=RECIPIENTS/CN=PDAVIS1>', 'Drew Fossum', 'Steven J Kean',
         'Kitchen, Louise </O=ENRON/OU=NA/CN=RECIPIENTS/CN=LKITCHEN>', 'James D Steffes',
         'Mark Taylor', 'Watson, Kimberly </O=ENRON/OU=NA/CN=RECIPIENTS/CN=KWATSON>',
         'Matthew Lenhart', 'Scott Neal', 'Robin Rodrigue', 'Susan J Mara', 'Daren J Farmer', 'Gerald Nemec',
         'Schedule Crawler<pete.davis@enron.com>', 'John J Lavorato', 'Dan J Hyvl', 'Eric Bass', 'Susan Scott',
         'Darron C Giron', 'Michelle Cash', 'Chris Germany', 'Chris Dorland', 'Maureen McVicker', 'Jeff Dasovich',
         'Phillip K Allen', 'Mark E Haedicke', 'John Arnold',
         'Mary Hain', 'Tana Jones',
         'Mike McConnell', 'Jeffrey A Shankman', 'Vince J Kaminski', 'Enron Announcements', 'David W Delainey',
         'Sally Beck']
TOP55_SORT = ['Kay Mann',
              'Vince J Kaminski',
              'Jeff Dasovich',
              'Enron Announcements',
              'Sara Shackleton',
              'Tana Jones',
              'Chris Germany',
              'Schedule Crawler<pete.davis@enron.com>',
              'Steven J Kean',
              'Kate Symes',
              'Eric Bass',
              'Matthew Lenhart',
              'Sally Beck',
              'Debra Perlingiere',
              'Drew Fossum',
              'Carol St Clair',
              'Benjamin Rogers',
              'Gerald Nemec',
              'Davis, Pete </O=ENRON/OU=NA/CN=RECIPIENTS/CN=PDAVIS1>',
              'David W Delainey',
              'Jeffrey A Shankman',
              'John Arnold',
              'Mike McConnell',
              'Daren J Farmer',
              'Phillip M Love',
              'Mark Taylor',
              'Richard B Sanders',
              'Robin Rodrigue',
              'John J Lavorato',
              'Mark E Haedicke',
              'Susan M Scott',
              'Susan Scott',
              'Elizabeth Sager',
              'Darron C Giron',
              'Steffes, James D. </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JSTEFFE>',
              'Dasovich, Jeff </O=ENRON/OU=NA/CN=RECIPIENTS/CN=JDASOVIC>',
              'Phillip K Allen',
              'Germany, Chris </O=ENRON/OU=NA/CN=RECIPIENTS/CN=CGERMAN>',
              'Dan J Hyvl',
              'Susan J Mara',
              'James D Steffes',
              'Kitchen, Louise </O=ENRON/OU=NA/CN=RECIPIENTS/CN=LKITCHEN>',
              'Michelle Cash',
              'Watson, Kimberly </O=ENRON/OU=NA/CN=RECIPIENTS/CN=KWATSON>',
              'Mary Hain',
              'Enron General Announcements </O=ENRON/OU=NA/CN=RECIPIENTS/CN=MBX_ANNCENRON>',
              'Chris Dorland',
              'Scott Neal',
              'Outlook Migration Team <Outlook Migration Team/Corp/Enron@ENRON>',
              'Maureen McVicker',
              ]
